grommet/grommet-site

- src/screens/Home.js
Can't highlight text & click on "GitHub" button.
> Fix nav blocking content

- package.json
- public/package.json
- src/screens/Examples.js
- src/screens/Try.js
- src/screens/Use.js
Changes links from HTTP to HTTPS in appropriate places; fixes issue #32
> update HTTP links to HTTPS in examples, try, use, and package files

- package.json
Update to `syled-components` v4 to fix issue #35.
> Update styled-compenents dependency from v3 to v4

- package.json
- yarn.lock
this will fix the playground in production
> downgrading react-live to avoid issues with react context

- src/components/Content.js
- src/components/Nav.js
- src/components/playground/examples/hello-world.js
- src/components/playground/examples/theme.js
- webpack.config.js
- yarn.lock
Buble has been fixed.
https://github.com/Rich-Harris/buble/issues/159#issuecomment-432348704
> Added playground back.

- src/screens/Menu.js
- src/screens/Paragraph.js
- src/screens/Select.js
- src/screens/Stack.js
- src/screens/Text.js
- src/screens/TextArea.js
- src/screens/TextInput.js
> Theme docs for components

- src/screens/Home/Start.js
- src/screens/Use.js
- src/structure.js
- yarn.lock
> Updating links to grommet icons

- src/components/Doc.js
- src/screens/Markdown.js
> fixing markdown link example

- package.json
- yarn.lock
Please let's not update react-live until this PR is merged:
https://github.com/FormidableLabs/react-live/pull/103
> Fixed react-live version.

- public/_redirects
> redirect from /grommet-icons to icons.grommet.io

- src/App.js
- yarn.lock
fixes issue #63 
https://stackoverflow.com/a/18573599/2811244
> Fix component pages to land on the top of the page

- src/screens/Heading.js
https://github.com/grommet/grommet/issues/2851
> Heading - improve color example

- src/screens/Use.js
Fixes #87 
@ShimiSun I figured out how to fix it :slightly_smiling_face:
> Fix broken link in /use

- src/screens/Color.js
> The color pallette.
pallette :arrow_right: palette
> Fix typo in Color screen

- src/screens/Home/index.js
Solves the discussion and inputs from this issue https://github.com/grommet/grommet/issues/3155
> adds PWA doc support

- src/screens/Docs/GettingStarted.js
Added to getting started page by putting a link to new color properties wiki page
> Added link to new color wiki page

- src/screens/Home/Start.js
> #112 remove scrollBeyondLastLine option in Monaco editor

- src/screens/ResponsiveContext.js
> Refactored ResponsiveContext screen to use hooks

- src/components/Doc/Doc.js
- src/screens/Footer.js
- src/screens/Header.js
- src/screens/Main.js
- yarn.lock
> Added Doc.isA for Header, Main, and Footer 

- src/screens/Docs/GettingStarted.js
- yarn.lock
Closing other branch, fixing issues with yarn.
adds blog link to getting started docs
> added blog link

- src/screens/Box.js
- yarn.lock
Update background docs for box to have repeat and size
> Update background docs for Box

- src/screens/Box.js
- yarn.lock
Fixes https://github.com/grommet/grommet/issues/3837
> Update Box docs for optional gap values

- src/screens/Anchor.js
- yarn.lock
removed primary from anchor example
> removed primary from anchor example

- src/screens/Heading.js
- src/screens/Paragraph.js
- src/utils/props.js
- yarn.lock
The Heading `margin` doesn't show the 'none' option. This PR attempts to fix it.
> Change margin to include 'none'

- src/screens/Form.js
- yarn.lock
Closes https://github.com/grommet/grommet/issues/3852
> Updated Form example to be accessible

- public/index.html
- src/screens/Home/Message.js
- src/screens/Home/Tools.js
- src/screens/Home/index.js
- yarn.lock
I'm exploring accessibility tool and came up with these fixes.
> Fix accessibility issues on the landing page

- src/screens/RadioButtonGroup.js
- yarn.lock
Related to https://github.com/grommet/grommet/pull/4208
> Added example of types for RadioButtonGroup

- src/components/Content.js
- src/screens/Components/index.js
- src/screens/Components/items.js
- src/screens/Tip.js
- src/structure.js
- yarn.lock
Related to https://github.com/grommet/grommet/issues/4599
> Added Tip component

- src/screens/DataTable.js
- yarn.lock
Currently, DataTable doesn't document the theme props, this PR fixes it.
> Changed DataTable to doc the theme styles

- README.md
- src/screens/Form.js
- Fix issue #190
- Also remove references to npm from README.md as this is a yarn-based project.
> Fix a typo in the sample code for the Form component.

- netlify.toml
- tools/build-static-site.js
Modifying build script to account for minified grommet.js now resulting in its own chunk when bundled.
Closes https://github.com/grommet/grommet-site/issues/197
Need to verify https://github.com/grommet/grommet-site/issues/197#issuecomment-758088397
> Update build script to account for grommet minified file

- yarn.lock
Updated grommet stable to include textinput fix for the site's search
> Updated grommet stable to include textinput fix for the site's search

- src/screens/Box.js
- yarn.lock
> Updated Box animation prop

- src/screens/Avatar.js
- src/utils/genericThemeExamples.js
- yarn.lock
Avatar doc uses the new format for documentation
> Updated Avatar doc to new format

- src/screens/AnnounceContext.js
- yarn.lock
Announce Context doc uses the new format for documentation
> Updated Announce Context doc to new format

- src/screens/Accordion.js
Accordion doc uses the new format for documentation
> Updated Accordion doc to new format

- src/screens/Calendar.js
- src/utils/themeDocUtils.js
Calendar uses new format for documentation
> Updated Calendar doc to new format

- src/components/Doc/ComponentDoc.js
- src/screens/Card.js
Card uses new documentation format
> Updated Card doc to new format

- src/screens/Carousel.js
Carousel uses new documentation format
> Updated Carousel doc to new format

- src/screens/Chart.js
- yarn.lock
Chart doc uses new format
issue #233
> Updated Chart doc to new format

- src/screens/CheckBoxGroup.js
CheckBoxGroup uses new format for documentation
issue #233
> Updated CheckBoxGroup doc to new format

- src/screens/Collapsible.js
Collapsible doc uses new format
Issue #233
> Update Collapsible doc to new format

- src/screens/Color.js
Color doc uses new format
Issue #233
> Updated Color doc to new format

- src/screens/DataChart.js
DataChart uses new format for documentation
Issue #233
> Updated DataChart doc to new format

- src/screens/DataTable.js
DataTable doc uses new format
Issue #233
> Update DataTable doc to new format

- src/screens/DateInput.js
DateInput uses new format
Issue #233
> Updated DateInput doc to new format

- src/screens/Diagram.js
Diagram uses new format
Issue #233
> Updated Diagram doc to new format

- src/screens/Distribution.js
Distribution uses new documentation format
Issue #233
> Updated Distribution doc to new format

- src/screens/Drop.js
- yarn.lock
Drop uses new documentation format
Issue #233
> Updated Drop doc to new format

- src/screens/DropButton.js
DropButton uses new doc format
Issue #233
> Updated DropButton doc to new format

- src/screens/FileInput.js
- src/utils/genericPropExamples.js
- src/utils/themeDocUtils.js
FileInput uses new documentation format
Issue #233
> Updated FileInput doc to new format

- src/screens/Image.js
Image doc uses new format
Issue #233
> Updated Image doc to new format

- src/screens/InfiniteScroll.js
InfiniteScroll doc uses new format
Issue #233
> Updated InfiniteScroll doc to new format

- src/screens/Keyboard.js
> Updated Keyboard to new format

- src/screens/Header.js
Header doc uses new format
Issue #233
> Updated Header doc to new format

- src/screens/Grid.js
Grid doc uses new format
Issue #233
> Updated Grid doc to new format

- src/screens/FormField.js
FormField uses new documentation format
Isse #233
> Updated FormField doc to new format

- src/screens/List.js
- src/utils/genericThemeExamples.js
List doc uses new format
Issue #233
> Updated List doc to use new format

- src/screens/Main.js
Main doc uses new format
Issue #233
> Updated Main doc to new format

- src/screens/Markdown.js
Markdown doc uses new format
Issue #233
> Updated Markdown doc to new format

- src/screens/MaskedInput.js
- src/utils/themeDocUtils.js
MaskedInput doc uses new format
Issue #233
> Updated MaskedInput doc to new format

- src/screens/Menu.js
Menu doc uses new format
Issue #233
> Updated Menu doc to new format

- src/screens/Meter.js
- src/utils/genericThemeExamples.js
Meter uses new format
Issue #233
> Updated Meter doc to new format

- src/screens/Nav.js
Nav doc uses new format
Issue #233
> Updated Nav doc to new format

- src/screens/Calendar.js
add prop `messages` to calendar docs
> update calendar messages docs

- src/screens/Pagination.js
Pagination doc uses new format
Issue #233
> Updated Pagination doc to new format

- src/screens/Paragraph.js
Paragraph doc uses new format
Issue #233
> Updated Paragraph doc to new format

- src/screens/RadioButton.js
RadioButton doc uses new format
Issue #233
> Updated RadioButton doc to new format

- src/screens/RadioButtonGroup.js
RadioButtonGroup doc uses new format
Issue #233
> Updated RadioButtonGroup doc to new format

- src/screens/RangeSelector.js
RangeSelector doc uses new format
Issue #233
> Updated RangeSelector doc to new format

- src/screens/ResponsiveContext.js
ResponsiveContext uses new format
Issue #233
> Updated ResponsiveContext doc to new format

- src/screens/Select.js
Select doc uses new format
Issue #233
> Updated Select doc to new format

- src/screens/Sidebar.js
Sidebar doc uses new format
Issue #233
> Updated Sidebar doc to new format

- src/screens/SkipLinks.js
SkipLinks doc uses new format
Issue #233
> Updated SkipLinks doc to new format

- src/screens/Spinner.js
Spinner doc uses new format
Issue #233
> Updated Spinner doc to new format

- src/components/Doc/ComponentDoc.js
- src/screens/Table.js
- src/utils/themeDocUtils.js
Table doc uses new format
Issue #233
> Updated Table doc to new format

- src/screens/Tabs.js
Tabs doc uses new format
Issue #233
> Updated Tabs doc to new format

- src/screens/Text.js
Text doc uses new format
Issue #233
> Updated Text doc to new format

- src/screens/TextArea.js
TextArea doc uses new format
Issue #233
> Updated TextArea doc to new format

- src/screens/TextInput.js
TextInput doc uses new format
Issue #233
> Updated TextInput doc to new format

- src/screens/ThemeContext.js
ThemeContext doc uses new format
Issue #233
> Updated ThemeContext doc to new format

- src/screens/Tip.js
Tip doc uses new format
Issue #233
> Updated Tip component to new format

- src/screens/Video.js
Video doc uses new format
Issue #233
> Updated Video doc to new format

- src/screens/WorldMap.js
WorldMap uses new format
Issue #233
> Updated WorldMap doc to new format

- src/screens/RangeInput.js
RangeInput doc uses new format
Issue #233
> Updated RangeInput doc to new format

- src/screens/Form.js
Form doc uses new format
Issue #233
> Updated Form doc to new format

- src/screens/Avatar.js
- src/screens/Card.js
- src/screens/CheckBoxGroup.js
- src/screens/Drop.js
- src/screens/FileInput.js
- src/screens/Footer.js
- src/screens/Header.js
- src/screens/List.js
- src/screens/Main.js
- src/screens/Nav.js
- src/screens/Pagination.js
- src/screens/RadioButtonGroup.js
- src/screens/Sidebar.js
- src/screens/SkipLinks.js
- src/screens/Tip.js
This PR aims to:
- Resolve #223
- Removes codesandbox links from components that do not have a corresponding sandbox
> Fix: Removed invalid CodeSandbox links

- src/screens/Select.js
Adds an addition to prop type example
> add select prop type to docs

- src/screens/Button.js
- yarn.lock
Signed-off-by: GurkiranSingh <gurkiransinghk@gmail.com>
Added docs for the justify prop for the button.
Since, this change is only effective when there is an icon alongside of button. I am not sure how to write proper description for this. I am open to suggestions. Thank You.
[PR](https://github.com/grommet/grommet/pull/5591)
> Added docs for the justify prop for the button

- src/screens/Text.js
Add `bolder` and `lighter` to docs for Text weight
> add lighter and bolder to docs

- src/screens/List.js
Add `defaultIItemsProp` to docs in addition to PR  #5573
> add defaultItemsProp in the docs

- src/screens/NameValueList.js
Updating gap docs to match new default value coming from https://github.com/grommet/grommet/pull/5780
> Update namevaluelist gap

- src/screens/NameValueList.js
Updating documentation to align with: https://github.com/grommet/grommet/pull/5789
> Update NameValueList gap documentation

- src/screens/DataTable.js
- yarn.lock
This adds the documentation for DataTable's onUpdate addition and groupBy changes
to support lazy loading, especially of group data.
Part of feature [#5679](https://github.com/grommet/grommet/issues/5679)
for PR [#5716](https://github.com/grommet/grommet/pull/5716)
> DataTable documentation for onUpdate and groupBy changes

- src/screens/Grommet.js
- yarn.lock
Provide a more detailed description for the `full='min'` prop. Related to https://github.com/grommet/grommet/pull/5811
> Expand description for Grommet's full='min' prop

- yarn.lock
update yarn lock with recent grommet release
> update yarn per grommet release

- src/screens/List.js
- yarn.lock
Signed-off-by: GurkiranSingh <gurkiransinghk@gmail.com>
Doc are added for the List Component `itemKey` prop.
https://github.com/grommet/grommet/pull/5872
> List Component - itemKey prop

- src/screens/Tag.js
- yarn.lock
Added the size property and theme properties documentation to the Tag component.
> Added size property and theme details to Tag

- src/screens/Notification.js
- yarn.lock
> add docs for toast position

- src/screens/DateInput.js
- yarn.lock
Signed-off-by: GurkiranSingh <gurkiransinghk@gmail.com>
Added icon prop doc for DateInput.
https://github.com/grommet/grommet/pull/5911
> Added icon prop doc for DateInput

- src/screens/Drop.js
- src/screens/DropButton.js
- yarn.lock
- updates guidance around `align` property for both drop and drop button
> Fix/drop-memo-doc: updated doc for memoizing align

- src/screens/Video.js
> Update Video doc around controls 

- src/screens/Header.js
- yarn.lock
> add sticky prop to docs

- src/components/Nav.js
- yarn.lock
Previously the docs button could only be found at the bottom of the homepage. This updates the nav at the top of the page to include the docs button.
> Add docs button to nav

- src/screens/Anchor.js
- yarn.lock
Added documentation about `anchor.gap`.
> Add Anchor theme gap docs

- src/screens/List.js
- yarn.lock
- Adds prop documentation for List `disabled` (https://github.com/grommet/grommet/pull/6111).
- Adds related theme documentation.
> List - Add documentation for disabled prop

- src/screens/Notification.js
- yarn.lock
Adds missing notification:
Closes https://github.com/grommet/grommet-site/issues/379
> Add notification docs

- src/screens/PageHeader.js
- yarn.lock
Updating docs to align with: https://github.com/grommet/grommet/pull/6131
> Update PageHeader docs default values

- src/screens/PageHeader.js
- yarn.lock
Documents `pageHeader.pad`
Related to and dependent upon https://github.com/grommet/grommet/pull/6152 (merged)
Related to https://github.com/grommet/hpe-design-system/issues/2603
> Add pageHeader.pad theme documentation

- src/screens/PageHeader.js
- yarn.lock
Children is no longer supported by PageHeader.
> Remove children from PageHeader docs

- src/screens/Menu.js
- yarn.lock
Added doc updates for https://github.com/grommet/grommet/pull/6162 and https://github.com/grommet/grommet/pull/6201
> Add doc changes for grouped menu

- src/screens/Paragraph.js
- yarn.lock
This adds the `maxLines` property to Paragraph.
> Added doc for Paragraph maxLines

- src/screens/Notification.js
> Add info to Notification prop

- src/components/Content.js
- src/screens/Button.js
- src/screens/Docs/GettingStarted.js
- src/screens/Docs/GlobalTheme.js
- src/screens/Docs/index.js
- src/utils/genericThemeExamples.js
Add a page to the docs that shows the global theme properties
> Add global theme props documentation

- src/screens/Notification.js
Added the autoClose prop to the documentation and improved the description
> Add `autoClose` to `toast` Notification documentation

- src/screens/PageHeader.js
Wait to merge until https://github.com/grommet/grommet/pull/6279 merges.
> Add PageHeader size docs

- src/components/Content.js
- src/screens/Docs/Stable.js
- src/screens/Docs/index.js
- yarn.lock
> add directions for how to use stable branch

- src/components/Doc/ComponentDoc.js
- src/components/Doc/Properties.js
- src/components/Doc/Property.js
- src/screens/SelectMultiple.js
- yarn.lock
Adds ability to mark components and specific prop as only being available on the stable branch.
https://github.com/grommet/grommet-site/pull/415 should be merged first so the links to the stable branch in this PR go to the stable branch document on the site.
Closes https://github.com/grommet/grommet-site/issues/362
> Stable notification

- src/App.js
- src/screens/Color.js
Show all the colors available, grouped by names we know, but allowing for theme specific color names that are just used via indirect reference.
> Restructured Color page

- src/screens/Avatar.js
- src/screens/CheckBox.js
- src/screens/DateInput.js
- src/screens/Notification.js
- yarn.lock
Adds the following to docs:
`checkbox.hover.extend`
`a11yTitle` Avatar
adds node as an option for Notification `message` prop 
`dateInput.container.round`
> add docs for October release

- src/screens/Grommet.js
- yarn.lock
This PR updates the `themeMode` docs according to the changes made for issue #6397. 
Screenshot of the change -
> Updated themeMode docs

- src/screens/Menu.js
- yarn.lock
Clarify wording of grouped menu items.
> Update grouped menu docs

- src/screens/Grommet.js
- src/screens/Notification.js
- yarn.lock
Adds `icon` and `time` props to notification and removes stable flag from `themeMode`
https://github.com/grommet/hpe-design-system/issues/2949
> Update docs pre 2.28.0 grommet release

- src/screens/SelectMultiple.js
- yarn.lock
Fixes link reported by https://hpe.slack.com/archives/C04LMJWQT/p1672963506177819
> Fix SelectMultiple storybook link

- src/screens/Calendar.js
- src/screens/DataSearch.js
- yarn.lock
Some tweaks to the Calendar and DataSearch docs. Related to https://github.com/grommet/hpe-design-system/issues/3086
> Adjust DataSearch and Calendar docs before February release

- src/screens/Data.js
- yarn.lock
[Deploy Preview](https://deploy-preview-460--upbeat-ardinghelli-95952e.netlify.app/data#properties)
Update the Data Component documentation for the `properties` prop on the Grommet documentation site here: https://v2.grommet.io/data#properties. Add a nested property object example that contains options and allows the caller to specify how the property label renders (see the `status` object in the screenshot).
Related to https://github.com/grommet/hpe-design-system/pull/3136
> Update Data Component 'Properties' Documentation

- src/components/Content.js
- src/screens/Docs/Icons.js
- src/screens/Docs/index.js
- src/structure.js
- yarn.lock
Documents props and theme props that can be used with grommet icons
related to https://github.com/grommet/grommet-icons/issues/305
> Add icons page to docs

- src/screens/Button.js
- yarn.lock
> Add Button `pad` docs

- src/screens/Button.js
- src/screens/FormField.js
Added docs for the following PRs:
https://github.com/grommet/grommet/pull/6656 - button busy
https://github.com/grommet/grommet/pull/5943 - form field validation
> Add documentation for button busy and FormField validateOn

- src/components/Content.js
- src/screens/Components/index.js
- src/screens/Components/items.js
- src/screens/Toolbar.js
- src/structure.js
- yarn.lock
Closes https://github.com/grommet/grommet-site/issues/474
> Add documentation for Toolbar component

- src/screens/Meter.js
- src/screens/Select.js
- src/screens/SelectMultiple.js
- Documented `reverse` prop on Meter https://github.com/grommet/grommet/pull/6398
- Added node option to `searchPlaceholder` for Select and SelectMultiple https://github.com/grommet/grommet/pull/6811
- Documented `select.emptySearchMessage` for Select and SelectMultiple https://github.com/grommet/grommet/pull/6815
> Update docs pre June 2023 release

- src/screens/Box.js
- yarn.lock
You can change the behavior of Box's gap by setting `options={{box: { cssGap: true } }}` on the Grommet container. This is documented on the Grommet options prop but not on the Box gap prop. This PR makes note of this on the Box gap prop description.
Closes https://github.com/grommet/grommet-site/issues/480
> Document Grommet's box cssGap option on Box `gap` prop

- src/screens/PageHeader.js
Added PageHeader responsive property.
Fixes grommet/grommet#6838
> Added PageHeader responsive property

- src/screens/Chart.js
- src/screens/DataChart.js
Update the docs pre grommet release. Added doc changes for https://github.com/grommet/grommet/pull/6799
> Update `bounds` and add `direction in DataChart and Chart

- src/screens/PageHeader.js
- src/screens/Select.js
- src/screens/SelectMultiple.js
- yarn.lock
There were a couple of typos in Select and SelectMultiple.
And since I was there, I added the `level` prop to PageHeader.
> minor fixes to select/selectMultiple, added level to PageHeader

- src/screens/DataTable.js
- src/screens/Grommet.js
- src/screens/RadioButton.js
- src/screens/Tag.js
- yarn.lock
- Added `radiobutton.check.background.color` to RadioButton. ([#5243](https://github.com/grommet/grommet/pull/5243))
- Added `tag.icon.remove` to Tag to allow the icon to be provided from the theme. ([#6960](https://github.com/grommet/grommet/pull/6960))
> added documents for enhancements

- src/screens/Data.js
- src/screens/DataFilter.js
Add documentation related to this PR that added `step` to DataFilter range: https://github.com/grommet/grommet/pull/6942
> Add documentation for DataFilter step

- src/screens/Data.js
- yarn.lock
Added docs changes related to https://github.com/grommet/grommet/pull/7046
> Add sort and filter to properties in Data

- src/screens/Data.js
- src/screens/DataFilter.js
- src/screens/DataFilters.js
- yarn.lock
Closes https://github.com/grommet/grommet/issues/6761
> Add docs about default filter types

- src/screens/DataSearch.js
- yarn.lock
Adds documentation for the `updateOn` property for `DataSearch`. See also [PR #7110](https://github.com/grommet/grommet/pull/7110)
> DataSearch updateOn doc

- src/screens/Data.js
- src/screens/DataSummary.js
- src/screens/Grommet.js
- yarn.lock
Update docs based on fixes made by https://github.com/grommet/grommet/pull/7116.
Will fix yarn.lock once other code has been approved.
> Update Data docs

- src/screens/Grommet.js
- src/screens/SelectMultiple.js
documentation for https://github.com/grommet/grommet/pull/7104
> add selectMultiple i18n varibles

- src/screens/DataFilters.js
- yarn.lock
In the DataFilters doc show that `layer` and `drop` props are `false` by default. I also changed the example on this page to show DataFilters inline instead of in a drop to give people a better idea of the default behavior.
> Update DataFilters doc to better convey that inline is the default behavior

- src/screens/List.js
- yarn.lock
Add `list.primaryKey` documentation 
https://github.com/grommet/grommet/pull/7136
> add documentation to support new feature in grommet 7136

- src/screens/DateInput.js
- src/screens/Grommet.js
- src/screens/RangeInput.js
- src/screens/TextInput.js
- yarn.lock
Added doc changes for the following PRs: 
RangeInput wheel https://github.com/grommet/grommet/pull/7130
Readonly https://github.com/grommet/grommet/pull/7123
> Add doc changes pre 2.36.0 release

- src/screens/Box.js
- yarn.lock
added behavior that was enhanced here https://github.com/grommet/grommet/pull/7147
> Add css gap

- src/screens/Pagination.js
- yarn.lock
Adds `summary` and `stepOptions`
> add summary and stepOptions

- src/screens/Box.js
- src/screens/DataTableColumns.js
- src/screens/Skeleton.js
- yarn.lock
Add Skeleton `extend`
Add `round` to responsive doc
Add `pinned` behavior
> add docs for new enhancements for April release

- src/screens/Anchor.js
- src/screens/ToggleGroup.js
- yarn.lock
Add the `tip` option in toggleGroup
Add the `anchor.icon.color` documentation
> add documentation prior to release

- src/screens/Anchor.js
- src/screens/ToggleGroup.js
- yarn.lock
Added docs for these PRs:
https://github.com/grommet/grommet/pull/7258
https://github.com/grommet/grommet/pull/7236
Closes https://github.com/grommet/grommet-site/issues/520
> Changes for 2.39.0 grommet release

- src/screens/Button.js
- src/screens/Drop.js
- yarn.lock
Added theme.button.intelligentPad to Button. (#7307)
Added a check to respect the autoFocus setting within Drop. (#7322)
> add button intelligentPad plus restrictFocus wording

- src/screens/Select.js
- src/screens/SelectMultiple.js
Updates the documentation to account for the new theming https://github.com/grommet/grommet/pull/7396
---
Let me know if wording is correct. I based mine on what was already in the docs.
> Add clear hover theming to Select and SelectMultiple components

- src/screens/Grommet.js
- yarn.lock
Add documentation for Meter messages in the Grommet component docs page
Functionality add here: https://github.com/grommet/grommet/pull/7445
> Document meter messages in Grommet component

- yarn.lock
update yarn lock file to get the latest grommet
> update yarn lock file to get the latest grommet

- src/screens/Calendar.js
- yarn.lock
updated yarn.lock & add `level` prop to Calendar
> add calendar level prop

- src/screens/Calendar.js
Add docs for calendar.day.adjacent.color prop added in https://github.com/grommet/grommet/pull/7473
> Add docs for calendar.day.adjacent.color

- src/screens/Box.js
- yarn.lock
add documentation for https://github.com/grommet/grommet/pull/7533
> add responsive container

- src/screens/TextInput.js
- yarn.lock
let users know that this prop may not be wcag compliant
> add note for default suggestion

- src/screens/Accordion.js
- src/screens/Avatar.js
- src/screens/Calendar.js
- src/screens/Data.js
- src/screens/DataTable.js
- src/screens/DateInput.js
- src/screens/FileInput.js
- src/screens/Grommet.js
- src/screens/Pagination.js
- src/screens/SkipLinks.js
- src/screens/Tabs.js
- src/screens/Tag.js
- src/screens/TextInput.js
- yarn.lock
Add documentation for the following 
https://github.com/grommet/grommet/pull/7570
https://github.com/grommet/grommet/pull/7571
https://github.com/grommet/grommet/pull/7590
> add docs for May release

- src/screens/Meter.js
- yarn.lock
added the docs from this PR 
https://github.com/grommet/grommet/pull/7712
> add meter gap docs
