grommet/grommet-site

src/screens/Home.js
Fixes issue #27 by changing the path on the Getting Started `RoutedButton` on the home page from `path='components'` to `path='/components'`
=> update get started button path on home screen

src/screens/Home/index.js
Links still referred to the NEXT tree.
=> fix link to github repo

src/screens/Home/Start.js
Caught a spelling error on the home page, thought I'd make myself useful and fix it.
=> Spelling error in Start.js

src/components/Search.js
Fixes this error in browser that don't support `.flat()`:
Source: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat#reduce_and_concat
=> Update Search.js fix .flat() function undefined error

src/screens/Text.js
`sematic` :arrow_right: `semantic`
As seen on the [components page](https://v2.grommet.io/components#Type)
=> Fix typo in Text screen

src/components/Doc/Doc.js, src/screens/Accordion.js, src/screens/Chart.js, src/screens/Table.js, src/screens/Tabs.js
I noticed that whenever there is more than one `Doc` component listed in the Grommet components, the document.title is being overridden. 
I allowed Doc to accept the prop `title` so the title can be set to an explicit title if needed.
This issue reproduces for Accordion, Chart, Tabs & Table.
example of the problem:
=> fix override of title on Doc

src/screens/Box.js
This is to resolve grommet/grommet#2959
There's no documentation for Box border styles at Grommet website.
Border styles work as expected. grommet/grommet#2604
This PR adds the said documentations.
=> Added border style to Box's documentation

src/Router.js
Currently when route changes scroll position doesn't
reset. As a result when a user reaches to bottom of
a page & changes route, the most important part of
next route is not immediately visible. With scroll
reset on route changes, user sees the top of next route
first.
Fixes #106
=> fix: add scroll position reset to route changes

src/components/Doc/Value.js
In case prop type is a number, the site isn't displaying the defaultValue.
This fix is displaying the defaultValue when the prop type is a number.
See the following examples for reference/testing:
InfiniteScroll-> step should show default value of 50. https://v2.grommet.io/infinitescroll#step
RangeSelector -> max or min props should show actual values.
https://v2.grommet.io/rangeselector#max
https://v2.grommet.io/rangeselector#min
https://v2.grommet.io/rangeselector#step
=> Fix defaultValue display for 'number' prop-type 

src/screens/Docs/index.js
The existing phrasing seems like it was a list of three items as opposed to a question and response. This makes it more clear upon skimming that it's question and then 2 links as answers.
=> Adjust phrasing on docs page

src/screens/Accordion.js, src/screens/Chart.js, src/screens/Docs/index.js, src/screens/Tabs.js
This PR resolves the issue noted in Issue #122. Chart has a second item that needed to be labeled "Calc" and Accordion has a second item that needed to be labeled "Accordion Panel".
=> Update Accordion Panel and Calc Titles

src/screens/Docs/index.js, src/screens/ResponsiveContext.js
Responsive Context had theme docs that were not displaying. This PR allows any theme docs to be displayed.
Local testing has been done to see that this change does display theme docs.
=> Responsive context docs

src/screens/Home/Accessible.js, src/screens/Home/Layouts.js, src/screens/Home/Messages.js, src/screens/Home/index.js, src/screens/Paragraph.js, yarn.lock
While updating yarn.lock dependencies to include some site changes, I ran into `react/no-unescaped-entities` errors that required some semantic changes, I'm indifferent about this rule and don't mind removing it in case you are not loving it or disagree with it. 
I'm guessing the errors are showing now since I've updated some lint dependencies on the yarn.lock, as those errors were not shown before.
Most of the errors were fixed by `yarn lint-fix`, I had to fix Paragraph.js manually.
More details about the rule can be found here:
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md
=> updating dependencies and lint-fix

src/components/Doc/Code.js
MonacoEditor provides tooltip explanations for hovering over various components and attributes in the code.
The tooltip gets cut off from the top due to the hidden overflow attribute applied to the parent Box.
Removing the overflow attribute does not appear to effect anything else inside the box.
=> MonacoEditor tooltips get cut off inside their Box 

package.json, src/components/Nav.js, src/screens/Anchor.js, src/screens/Button.js, src/screens/Chart.js, src/screens/Diagram.js, src/screens/Distribution.js, src/screens/Home/Themable.js, src/screens/Home/Tools.js, src/screens/Home/index.js, src/screens/Meter.js, src/screens/Try.js, yarn.lock
The change looks good.
The only caveat IMO is the missing `accent-1` color on the hpe theme. 
grommet-site references `accent-1` multiple times, and since it is missing from the hpe theme, the site defaults to grommet's colors and it's missing the hpe color vibe.
Unless we decide to add `accent-1` color to the hpe theme, we will need to approach it on the site, I wasn't sure what supposed to replace the `accent-1` color in some places, for example on the components button
I don't think it will be right to replace it with `graph-0`, so I'm assuming we will want to use the brand color instead? In that case, if we will pick the brand color (or any other color) we will need to add an opinionated logic to the site to pick the `accent-1` color if the theme is the grommet theme, but to pick the …
=> Changed hpe theme package to point to stable

src/screens/CheckBoxGroup.js, src/screens/RadioButtonGroup.js, yarn.lock
Closes issue #4183 in grommet 
`RadioButtonGroup` and `CheckBoxGroup` are both made from boxes these both have a default gap that is being used. Users can change this so documentation was needed here to let users know that the gap was being set but can be changed. 
https://github.com/grommet/grommet/blob/master/src/js/components/CheckBoxGroup/CheckBoxGroup.js#L12
This is the case for both components.
Preview of what page will look like:
=> add to checkboxgroup and radiobuttongroup docs

package.json, yarn.lock
Now that we are no longer using NEXT branch of grommet-theme-hpe, we should point to stable like we do for Design System site.
=> Point to stable branch of grommet-theme-hpe

src/screens/Anchor.js, src/utils/themeDocUtils.js, yarn.lock
This pull request is part of an effort to [remove react-desc](https://github.com/grommet/grommet/issues/2976) from grommet and have the documentation be contained within grommet-site.
Previously grommet-site was getting the documentation from grommet, this PR creates the documentation as an object stored directly in the component file on grommet-site.
Steps to repeat process on other components:
1. In the `src/screens/<component>` file on grommet-site comment out everything in the export function and add `<div>{JSON.strigify(desc)}</div>` 
2. open the site to the correct component page and copy the output into `const desc =` variable
3. option + shift + F to format document
4. repeat for `themeDoc`
5. `import themeDocUtils` if necessary
6. remove `import { doc, themeDoc }`
=> Moved Anchor documentation from Grommet to be contained within site

src/components/Doc/PropExample.js, src/components/Doc/PropOptions.js, src/components/Doc/index.js, src/screens/Accordion.js, src/screens/Anchor.js, src/screens/Box.js, src/utils/genericPropExamples.js, src/utils/genericThemeExamples.js
Box doc uses the new format for documentation
Additional Changes:
`PropExample.js` - added `<pre>` tag so that examples will maintain indentation and line breaks but will also wrap when the screen is resized. This allowed for <Markdown> tags to be removed in `Accordion.js` and `genericPropExamples.js` because they were only being used to maintain indentation in examples.
`PropOptions.js` - added new file to handle example with "where .. could be" (See Box `background`)
`genericPropExamples.js` - made sure each generic example was wrapped in <PropertyValue>, this caused changes in `Accordion.js` and `Anchor.js`
=> Updated Box doc to new format

src/components/Doc/Description.js, src/screens/CheckBox.js, src/utils/genericPropExamples.js
CheckBox doc uses new format
Issue #233 
Description.js - added ability to disable styling markdown for examples that need it. See checked prop in CheckBox.js
genericPropExamples.js - GenericPad previously left out 'end' and 'start' options
=> Updated CheckBox doc to new format

src/components/Doc/ComponentDoc.js, src/components/Doc/DomProps.js, src/screens/Clock.js
Clock doc uses new format
issue #233 
Also updated ComponentDoc and DomProps to allow `intrinsicElement` to be an array or sting because Clock has two intrinsic elements
=> Updated Clock doc to new format

src/components/Doc/DomProps.js, src/screens/Accordion.js, src/screens/Calendar.js, src/screens/Card.js, src/screens/Carousel.js, src/screens/Chart.js, src/screens/CheckBoxGroup.js, src/screens/Clock.js, src/screens/DataChart.js, src/screens/DataTable.js, src/screens/Distribution.js, src/screens/Drop.js, src/screens/FormField.js, src/screens/Grid.js, src/screens/Markdown.js, src/screens/Paragraph.js
- Removes a console.log statement
- Removes period from initial component description at top of the page (periods should follow all other descriptions within the props and theme sections) 
- Fixes any typos 
- Removes duplicate descriptions (ex. "An object can be specified to distinguish horizontal margin, vertical margin, and margin on a particular side." is already stated in the object description of <GenericMargin />)
=> Final polish of docs

src/screens/Meter.js
Add in  `semicirlce` to Meter type 
This was an enhancement added to grommet 
https://github.com/grommet/grommet/pull/5463
=> add semicircle to meter type

src/Router.js, src/components/Page.js, src/screens/Components/index.js
Fixes doc links that reference a specific prop on a component page to scroll down to that section when you navigate to the link.
Closes #294
=> Fix prop anchor links to scroll to location

src/screens/FormField.js
This PR aims to:
- Resolve https://github.com/grommet/grommet/issues/5514
- Add notes on FormField's `name` prop to indicate to users that a name will be needed in order to use FormField's `validate` prop
=> Fix: Notes for name prop on FormField

.eslintrc, package.json, src/screens/Home/Message.js, src/screens/Home/Messages.js, src/screens/Home/Tools.js, src/screens/Home/index.js, src/screens/Image.js, src/screens/Spinner.js, src/screens/Try.js, yarn.lock
This PR adds the recommended configuration of `eslint-plugin-grommet` to grommet site. Additionally, I resolved the errors that were flagged by the linter (primarily missing alt-text on Images).
=> Add eslint-plugin-grommet and fix lint errors

src/screens/DateInput.js
Update documentation to include `messages` prop
| prop     | type   | default value |
| -------- | ------ | ------------- |
| messages | object | { enterCalendar: 'Calendar is open, press tab to enter the calendar',  exitCalendar: 'Exited calendar dialog' } |
See [#5471](https://github.com/grommet/grommet/pull/5471)
=> Add `messages` to DateInput documentation 

src/screens/List.js
Closes https://github.com/grommet/grommet-site/issues/308
Updates List's `onClickItem` prop example to show the event object's `item` property instead of `datum` which is not a property on the event object.
**Before**:
**After**:
=> Fix List onClickItem example

src/screens/FileInput.js
This PR aims to:
- Adds `maxSize` prop to FileInput docs in relation to grommet/grommet#5320
=> Feature: adding maxSize prop to FileInput docs

src/screens/Tabs.js
This PR Aims to resolve:
- A slight revision needed for Tabs' `alignControls` prop  in an issue found [here](https://github.com/grommet/grommet/issues/5448)
- Updates to the documentation to explain `alignControls` is in reference to how the tab controls align on the vertical axis
=> Tabs alignControl prop: editing description

src/screens/InfiniteScroll.js
The `scrollableAncestor` prop was removed from Grommet, the docs just needed updated to reflect this.
Closes https://github.com/grommet/grommet/issues/5691
=> Remove scrollableAncestor from InfiniteScroll docs

src/screens/FileInput.js
Clarifies that bytes refers to `binary` format.
=> Update FileInput maxSize docs

src/screens/Anchor.js
This PR aims to:
- add to the `as` prop documentation for `Anchor`
- add a component example for `as` prop
=> Feature: Anchor As Prop Extension

src/screens/DateInput.js
Place a `box` around `dateinput` so `dateinput` doesnt grow
Currently: 
FIx:
=> place a box around dateinput

src/screens/Select.js
Add function as an option for `valueLabel` and fix `valueKey` doc to show both object and function as options.
Associated grommet PR: https://github.com/grommet/grommet/pull/6020
=> Update Select docs to show valueLabel can be a function

src/screens/Docs/Browsers.js
Internet Explorer's end of life is June 15, 2022. We should remove it from the list of browsers we support
=> Remove Internet Explorer from supported browser list

src/screens/DataChart.js
Discovered while trying example at:
https://v2.grommet.io/datachart
=> Fix typo in DataChart granularity

src/screens/Box.js, src/screens/DataTable.js
Added necessary doc updates before releasing next version of grommet. Changes are related to the following pull requests:
https://github.com/grommet/grommet/pull/6038 - Make `as` prop on Box accept any React element
https://github.com/grommet/grommet/pull/6076 - Allow DataTable vertical align to be specified by prop
=> Add doc changes for PR's before grommet release

src/screens/Docs/Resources.js
Removed links to medium since we haven't been posting articles here in the past few years and also removed the link to codesandbox for every grommet component since we are moving away from using this and haven't kept it up to date when new components are added.
=> Remove links to medium and codesandbox for all components

src/screens/Tabs.js
The [responsive tabs](https://github.com/grommet/grommet/pull/6137) pull request on Grommet added the theme prop `tabs.step`. This pull request updates the docs to reflect this addition.
=> Added `tabs.step` prop to the Tabs theme doc

src/screens/DropButton.js
It isn't clear in the doc for DropButton that Button props can be passed to DropButton. This PR adds a section that tells users that DropButton is a Button and links to the Button documentation
=> Clarify that any Button prop can be passed to DropButton

src/screens/Button.js, src/screens/DateInput.js, yarn.lock
Added doc updates for the following pull requests before releasing grommet v2.25.0
Allow Button to accept elementType for `as` https://github.com/grommet/grommet/pull/6172
Allowing to reverse icon in DateInput https://github.com/grommet/grommet/pull/6160
=> Added missing doc updates before v2.25.0 release

src/components/Nav.js, src/screens/Button.js, src/screens/Components/Item.js, yarn.lock
Certain colors like "accent"/"neutrals" are deprecated in HPE theme. this improves theme rendering to make the site render better for non-grommet themes
GROMMET THEME (already looks like this):
HPE THEME (before and after):
before, difficult to see cards
after, aligns with grommet
Fixed color rendering in Nav:
before
after
=> Improve theme rendering from non-grommet themes

src/screens/Button.js, src/screens/CheckBox.js, src/screens/FormField.js, src/screens/Heading.js, src/screens/Menu.js
This includes the latest changes to Grommet that were not added to docs.
menu.item to the docs (added in this PR https://github.com/grommet/grommet/pull/6241/files)(https://hpe.slack.com/archives/D02977518F4/p1661876566258389)
button icon kind theme stuff to the docs from this PR https://github.com/grommet/grommet/pull/6297
add `formfield.checkBox.pad` to [docs](https://github.com/grommet/grommet/pull/6300)
Add weight to Heading to [docs](https://github.com/grommet/grommet/pull/6294)
=> Update docs 

src/screens/Box.js, src/screens/Docs/GlobalTheme.js, src/screens/Drop.js, src/screens/Grommet.js, src/screens/Layer.js, src/screens/Page.js
Adds documentation for: 
- backgrounds theme documentation
- the additional properties on the backgrounds object
Proposing we create a follow on issue to consolidate all references to BackgroundObject to a single source of truth.
=> Add backgrounds theme documentation

src/screens/CheckBoxGroup.js, src/screens/List.js, src/screens/Notification.js
Add missing info to the docs from the following pull requests:
- CheckBoxGroup defaultValue (https://github.com/grommet/grommet/pull/6331)
- List pinned (https://github.com/grommet/grommet/pull/6249)
- Notification theme changes (https://github.com/grommet/grommet/pull/6336)
=> Update docs before grommet release

src/screens/Grommet.js, src/screens/StarRating.js, src/screens/ThumbsRating.js, yarn.lock
Added doc changes for Grommet `options.box.cssGap` and added an intrinsic element for StarRating and ThumbsRating
Related to https://github.com/grommet/hpe-design-system/issues/3034
=> Doc changes before 2.29.0 release

src/screens/Button.js, src/screens/Calendar.js, src/screens/DataSearch.js, src/screens/Layer.js, src/screens/TextInput.js
The following PR adds: 
`width` for [TextInput](https://github.com/grommet/grommet/pull/6624)
`button.icon.size` for [Button](https://www.google.com/url?q=https://github.com/grommet/grommet/pull/6604&sa=D&source=docs&ust=1676574010377036&usg=AOvVaw0sxHqv4KFkvmEFDIaL2a3F)
`button.size.small.iconOnly.pad` for [Button](https://www.google.com/url?q=https://github.com/grommet/grommet/pull/6604&sa=D&source=docs&ust=1676574010377036&usg=AOvVaw0sxHqv4KFkvmEFDIaL2a3F)
`button.[kind].direction` for [Button](https://www.google.com/url?q=https://github.com/grommet/grommet/pull/6606&sa=D&source=docs&ust=1676573957254960&usg=AOvVaw3uCEkvmb2MJc_7zENq7J5A)
`ayer.overlay.backdopFilter` for [Layer](https://github.com/grommet/grommet/pull/6605)
=> add new properties per Feb release

src/screens/Button.js
This change was reverted on grommet so we should remove it from the docs
https://github.com/grommet/grommet/pull/6651
=> Remove button.icon.size

src/screens/SelectMultiple.js
Yarn is so woefully out of date here that Volta won't even run it, so I couldn't test this locally but it is a copy paste of the documentation from the regular Select so it should be solid.
=> Added missing labelKey documentation

src/screens/DataSearch.js
Added in the docs that 
```
DataSearch is a [TextInput](http://localhost:8567/textinput). You can customize it using the properties available in TextInput.
```
We have this wording already so just utilized this.
In DataSearch.js in grommet we have 
```
icon={<Search />}
type="search"
```
for the TextInput prop however being that this is a DataSearch hence Search the keyword not sure if we should add these in the docs as default open to suggestions
=> add dataSearch `as` TextInput

src/screens/DataTableColumns.js
DataTableColumns `options` prop also takes any `checkbox` props. Adding this in the description so users can know. One difference is that instead of `value` prop in CheckBox in DataTableColumns it needs a `property` passed in if an array of objects is given.
=> add in description for options to also take checkbox props

src/components/Search.js, src/structure.js, yarn.lock
Fixes #452 
These changes avoid multiple search results for the same name.
This also pre-calculates the `nameToPath` results for items in `structure` and for a name that appears both as a section name and a component name it gives priority to the component name path.
This fixes issues where Data always goes to the main components page rather than the Data component itself.
=> Fix issues with duplicate Data search results

src/screens/Heading.js
`heading.level` documentation incorrectly references `header.responsiveBreakpoint`. This PR changes it to `heading.responsiveBreakpoint` instead.
Related slack thread:
https://grommet.slack.com/archives/C09QQEG69/p1734376393309149
=> Fix typo in Heading level documentation

src/screens/DataTable.js
Based on Slack discussion, clarify when to use `primaryKey` instead of `primary` in columns object. In cases where the primary column gets hidden (for example with DataTableColumns), this can cause data to render incorrectly if `primaryKey` is not defined.
=> Clarify when to use primaryKey instead or columns.primary
